title: Kevin Dejbod
description: > 

  A Passionate Biomedical & ML Engineer that loves viewing the world with a pair of maths glasses. This is my portfolio where I share my projects, tutorials, and experiences in the field.


  <br><br>
  <a href="https://www.linkedin.com/in/kevin-dejbod/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> <a href="https://github.com/HeartBeatman"> <img src="https://img.shields.io/badge/GitHub-black?logo=GitHub"> </a>
  <br><br>

  <br><br>
  <a href="https://heartbeatman.github.io/Kevin/">Home</a>
  


  <br><br>
  <a href="https://heartbeatman.github.io/Kevin/opensource.html"><b>Projects</b></a>
  <br><br>

  <a href="https://heartbeatman.github.io/Kevin/Professional.html">Professional Experience</a>

  <br><br>
  <a href="https://heartbeatman.github.io/Kevin/research.html">Research</a>
  <br><br>

  <a href="https://heartbeatman.github.io/Kevin/Tutorials.html">Tutorials</a>
  <br><br>


theme: jekyll-theme-minimal
