title: Kevin Dejbod
description: >


  A Passionate Biomedical & ML Engineer that loves viewing the world with a pair of maths glasses. This is my portfolio where I share my projects, tutorials, and experiences in the field.
  <a href="research.md">Research Experience</a>
  <a href="projects.md">Projects</a>
  <a href="tutorials.md">Tutorials</a>
  <a href="experience.md">Experience</a>
  
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-dejbod/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> <a href="https://github.com/HeartBeatman"> <img src="https://img.shields.io/badge/GitHub-black?logo=GitHub"> </a>
  <br><br>

theme: jekyll-theme-minimal
