title: Kevin Dejbod
description: "Portfolio of Kevin Dejbod"
theme: jekyll-theme-minimal
author: Kevin Dejbod
email: kevin@example.com
social:
  - platform: Twitter
    username: kevindejbod
  - platform: LinkedIn
    username: kevindejbod
