title: Kevin Dejbod
description: >
  A Passionate Biomedical & ML Engineer that loves viewing the world with a pair of maths glasses.
  <br><br>
  <a href="#research.md)">Section 1</a>
  <br><br>
  <a href="#section2">Section 2</a>
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-dejbod/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a>
  <br><br>
  <a href="https://github.com/HeartBeatman"> <img src="https://img.shields.io/badge/GitHub-black?logo=GitHub"> </a>
  <br><br>

theme: jekyll-theme-minimal
